# Logistic Regression Heart Attack Classification

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import roc_curve
import warnings
warnings.filterwarnings("ignore")

## Problem statement

## Data Gathering

In [2]:
df=pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

## EDA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [4]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [10]:
df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

## Model Training

In [5]:
x=df.drop("target",axis=1)
y=df["target"]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=32,stratify=y)


In [9]:
## Create instance
model=LogisticRegression()

## Fit the Model
model.fit(x_train,y_train)



LogisticRegression()

## Model Evaluation

In [16]:
## Testing data
y_pred = model.predict(x_test)
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1], dtype=int64)

In [20]:
## For Testing
y_pred = model.predict(x_test)

cnf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n",cnf_matrix)

print("-"*65)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:",accuracy)
print("-"*65)

clf_report = classification_report(y_test, y_pred)
print("Classification report:\n",clf_report)

Confusion Matrix:
 [[30 11]
 [ 2 48]]
-----------------------------------------------------------------
Accuracy Score: 0.8571428571428571
-----------------------------------------------------------------
Classification report:
               precision    recall  f1-score   support

           0       0.94      0.73      0.82        41
           1       0.81      0.96      0.88        50

    accuracy                           0.86        91
   macro avg       0.88      0.85      0.85        91
weighted avg       0.87      0.86      0.85        91



In [21]:
## For Training
y_pred_train = model.predict(x_train)

cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion Matrix:\n",cnf_matrix)

print("-"*65)
accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy Score:",accuracy)
print("-"*65)

clf_report = classification_report(y_train, y_pred_train)
print("Classification report:\n",clf_report)

Confusion Matrix:
 [[ 75  22]
 [  9 106]]
-----------------------------------------------------------------
Accuracy Score: 0.8537735849056604
-----------------------------------------------------------------
Classification report:
               precision    recall  f1-score   support

           0       0.89      0.77      0.83        97
           1       0.83      0.92      0.87       115

    accuracy                           0.85       212
   macro avg       0.86      0.85      0.85       212
weighted avg       0.86      0.85      0.85       212



## Test single row

In [23]:
column=x.columns
column

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [29]:
x_test.head(1).T

41
age        48.0
sex         1.0
cp          1.0
trestbps  130.0
chol      245.0
fbs         0.0
restecg     0.0
thalach   180.0
exang       0.0
oldpeak     0.2
slope       1.0
ca          0.0
thal        2.0

In [33]:
age = 50.0
sex = 0
cp =0
trestbps= 130.0
chol = 285.0
fbs= 1
restecg= 1.0
thalach= 180.0
exang = 1.0
oldpeak = 0.2
slope = 1.0
ca = 0.0
thal = 2.0

In [34]:
array=np.array([age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal])
array

array([5.00e+01, 0.00e+00, 0.00e+00, 1.30e+02, 2.85e+02, 1.00e+00,
       1.00e+00, 1.80e+02, 1.00e+00, 2.00e-01, 1.00e+00, 0.00e+00,
       2.00e+00])

In [35]:
prediction=model.predict([array])[0]
prediction

1

In [37]:

project_data={"column":list(column)}
project_data

{'column': ['age',
  'sex',
  'cp',
  'trestbps',
  'chol',
  'fbs',
  'restecg',
  'thalach',
  'exang',
  'oldpeak',
  'slope',
  'ca',
  'thal']}

In [38]:
import json
with open("Heart.json","w") as f:
    json.dump(project_data,f)

In [41]:
import pickle
with open("Heart.pkl","wb") as f:
    pickle.dump(model,f)